/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace GrievanceContractOptimized {
  export type ComplaintStruct = {
    complainantIdHash: BytesLike;
    descriptionHash: BytesLike;
    attachmentHash: BytesLike;
    locationHash: BytesLike;
    submissionDate: BigNumberish;
    lastUpdated: BigNumberish;
    upvoteCount: BigNumberish;
    urgencyLevel: BigNumberish;
    statusCode: BigNumberish;
    isPublic: boolean;
  };

  export type ComplaintStructOutput = [
    complainantIdHash: string,
    descriptionHash: string,
    attachmentHash: string,
    locationHash: string,
    submissionDate: bigint,
    lastUpdated: bigint,
    upvoteCount: bigint,
    urgencyLevel: bigint,
    statusCode: bigint,
    isPublic: boolean
  ] & {
    complainantIdHash: string;
    descriptionHash: string;
    attachmentHash: string;
    locationHash: string;
    submissionDate: bigint;
    lastUpdated: bigint;
    upvoteCount: bigint;
    urgencyLevel: bigint;
    statusCode: bigint;
    isPublic: boolean;
  };

  export type EscalationRecordStruct = {
    fromStatus: BigNumberish;
    toStatus: BigNumberish;
    escalatedAt: BigNumberish;
    escalatedBy: AddressLike;
    reasonHash: BytesLike;
  };

  export type EscalationRecordStructOutput = [
    fromStatus: bigint,
    toStatus: bigint,
    escalatedAt: bigint,
    escalatedBy: string,
    reasonHash: string
  ] & {
    fromStatus: bigint;
    toStatus: bigint;
    escalatedAt: bigint;
    escalatedBy: string;
    reasonHash: string;
  };

  export type SlaRecordStruct = {
    expectedBy: BigNumberish;
    recordedAt: BigNumberish;
    breachedAt: BigNumberish;
    breached: boolean;
    noteHash: BytesLike;
  };

  export type SlaRecordStructOutput = [
    expectedBy: bigint,
    recordedAt: bigint,
    breachedAt: bigint,
    breached: boolean,
    noteHash: string
  ] & {
    expectedBy: bigint;
    recordedAt: bigint;
    breachedAt: bigint;
    breached: boolean;
    noteHash: string;
  };

  export type StatusAuditEntryStruct = {
    oldStatus: BigNumberish;
    newStatus: BigNumberish;
    changedAt: BigNumberish;
    changedBy: AddressLike;
    reasonHash: BytesLike;
  };

  export type StatusAuditEntryStructOutput = [
    oldStatus: bigint,
    newStatus: bigint,
    changedAt: bigint,
    changedBy: string,
    reasonHash: string
  ] & {
    oldStatus: bigint;
    newStatus: bigint;
    changedAt: bigint;
    changedBy: string;
    reasonHash: string;
  };

  export type UserStruct = {
    emailHash: BytesLike;
    aadhaarHash: BytesLike;
    locationHash: BytesLike;
    registrationDate: BigNumberish;
    isActive: boolean;
  };

  export type UserStructOutput = [
    emailHash: string,
    aadhaarHash: string,
    locationHash: string,
    registrationDate: bigint,
    isActive: boolean
  ] & {
    emailHash: string;
    aadhaarHash: string;
    locationHash: string;
    registrationDate: bigint;
    isActive: boolean;
  };
}

export interface GrievanceContractOptimizedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anonymousIdentityProofVerified"
      | "anonymousProofVerifier"
      | "assignComplaint"
      | "authorizedOperators"
      | "checkComplaintExists"
      | "checkUserExists"
      | "commitMerkleBatch"
      | "complaintExists"
      | "complaints"
      | "createAuditLog"
      | "createCivicPriority"
      | "emitComplaintVerificationCode"
      | "escalateComplaint"
      | "getComplaint"
      | "getComplaintEscalationHistory"
      | "getComplaintSla"
      | "getComplaintStatusHistory"
      | "getComplaintVerificationCode"
      | "getCounts"
      | "getResolutionCertificate"
      | "getResolutionCertificateTokenByComplaint"
      | "getUser"
      | "issueResolutionCertificate"
      | "issueResolutionCertificateToWallet"
      | "markComplaintSlaBreached"
      | "owner"
      | "recordAgentPerformance"
      | "recordComplaintSla"
      | "recordDuplicateAssessment"
      | "registerAnonymousComplaint"
      | "registerComplaint"
      | "registerUser"
      | "resolveComplaint"
      | "setAnonymousProofVerifier"
      | "setAuthorizedOperator"
      | "totalAuditLogs"
      | "totalComplaints"
      | "totalMerkleBatches"
      | "totalResolutionCertificates"
      | "totalUsers"
      | "transferOwnership"
      | "updateComplaintStatus"
      | "updateComplaintStatusWithReason"
      | "updateUpvoteCount"
      | "upvoteComplaint"
      | "userExists"
      | "users"
      | "verifyAnonymousIdentityProof"
      | "verifyHash"
      | "verifyMerkleProof"
      | "voteCivicPriority"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentPerformanceRecorded"
      | "AnonymousComplaintRegistered"
      | "AnonymousIdentityProofVerified"
      | "AnonymousProofVerifierUpdated"
      | "AuditLogCreated"
      | "AuthorizedOperatorUpdated"
      | "CivicPriorityCreated"
      | "CivicPriorityVoted"
      | "ComplaintAssigned"
      | "ComplaintEscalated"
      | "ComplaintLocationStored"
      | "ComplaintRegistered"
      | "ComplaintResolved"
      | "ComplaintSlaBreached"
      | "ComplaintSlaRecorded"
      | "ComplaintStatusAudited"
      | "ComplaintStatusUpdated"
      | "ComplaintUpvoted"
      | "ComplaintVerificationCodeCreated"
      | "CrossDepartmentCorruptionFlagged"
      | "DuplicateAssessmentRecorded"
      | "MerkleBatchCommitted"
      | "OwnershipTransferred"
      | "ResolutionCertificateIssued"
      | "ResolutionCertificateMinted"
      | "UpvoteAdded"
      | "UserLocationStored"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anonymousIdentityProofVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anonymousProofVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assignComplaint",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkComplaintExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUserExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "commitMerkleBatch",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "complaintExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "complaints",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuditLog",
    values: [string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createCivicPriority",
    values: [string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitComplaintVerificationCode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "escalateComplaint",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getComplaint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getComplaintEscalationHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getComplaintSla",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getComplaintStatusHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getComplaintVerificationCode",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getCounts", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getResolutionCertificate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResolutionCertificateTokenByComplaint",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getUser", values: [string]): string;
  encodeFunctionData(
    functionFragment: "issueResolutionCertificate",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "issueResolutionCertificateToWallet",
    values: [string, string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "markComplaintSlaBreached",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordAgentPerformance",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordComplaintSla",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDuplicateAssessment",
    values: [string, BytesLike, BytesLike, BytesLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAnonymousComplaint",
    values: [
      string,
      BytesLike,
      string,
      string,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerComplaint",
    values: [
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      boolean,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [
      string,
      string,
      string,
      BytesLike,
      BytesLike,
      BytesLike,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveComplaint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAnonymousProofVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAuditLogs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalComplaints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalMerkleBatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalResolutionCertificates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateComplaintStatus",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateComplaintStatusWithReason",
    values: [string, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUpvoteCount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upvoteComplaint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "verifyAnonymousIdentityProof",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHash",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMerkleProof",
    values: [BytesLike, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "voteCivicPriority",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "anonymousIdentityProofVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anonymousProofVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkComplaintExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkUserExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitMerkleBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complaintExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "complaints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAuditLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCivicPriority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitComplaintVerificationCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escalateComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComplaintEscalationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComplaintSla",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComplaintStatusHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComplaintVerificationCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCounts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getResolutionCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolutionCertificateTokenByComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueResolutionCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueResolutionCertificateToWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markComplaintSlaBreached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAgentPerformance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordComplaintSla",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDuplicateAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAnonymousComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAnonymousProofVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAuditLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalComplaints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMerkleBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalResolutionCertificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateComplaintStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateComplaintStatusWithReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUpvoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upvoteComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAnonymousIdentityProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyMerkleProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteCivicPriority",
    data: BytesLike
  ): Result;
}

export namespace AgentPerformanceRecordedEvent {
  export type InputTuple = [
    agentId: string,
    complaintId: string,
    resolvedCount: BigNumberish,
    escalatedCount: BigNumberish,
    duplicateFlags: BigNumberish,
    score: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    complaintId: string,
    resolvedCount: bigint,
    escalatedCount: bigint,
    duplicateFlags: bigint,
    score: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: string;
    complaintId: string;
    resolvedCount: bigint;
    escalatedCount: bigint;
    duplicateFlags: bigint;
    score: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AnonymousComplaintRegisteredEvent {
  export type InputTuple = [
    complaintId: string,
    commitmentHash: BytesLike,
    metadataHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    commitmentHash: string,
    metadataHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    commitmentHash: string;
    metadataHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AnonymousIdentityProofVerifiedEvent {
  export type InputTuple = [
    identityCommitment: BytesLike,
    verifiedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    identityCommitment: string,
    verifiedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    identityCommitment: string;
    verifiedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AnonymousProofVerifierUpdatedEvent {
  export type InputTuple = [verifier: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [verifier: string, timestamp: bigint];
  export interface OutputObject {
    verifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditLogCreatedEvent {
  export type InputTuple = [
    logId: string,
    action: string,
    userId: string,
    complaintId: string,
    details: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    logId: string,
    action: string,
    userId: string,
    complaintId: string,
    details: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    logId: string;
    action: string;
    userId: string;
    complaintId: string;
    details: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorizedOperatorUpdatedEvent {
  export type InputTuple = [
    operator: AddressLike,
    isAuthorized: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    isAuthorized: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    operator: string;
    isAuthorized: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CivicPriorityCreatedEvent {
  export type InputTuple = [
    priorityId: string,
    creatorHash: BytesLike,
    endsAt: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    priorityId: string,
    creatorHash: string,
    endsAt: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    priorityId: string;
    creatorHash: string;
    endsAt: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CivicPriorityVotedEvent {
  export type InputTuple = [
    priorityId: string,
    voter: AddressLike,
    voteCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    priorityId: string,
    voter: string,
    voteCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    priorityId: string;
    voter: string;
    voteCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintAssignedEvent {
  export type InputTuple = [
    complaintId: string,
    assignedTo: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    assignedTo: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    assignedTo: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintEscalatedEvent {
  export type InputTuple = [
    complaintId: string,
    fromStatus: BigNumberish,
    toStatus: BigNumberish,
    escalatedBy: AddressLike,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    fromStatus: bigint,
    toStatus: bigint,
    escalatedBy: string,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    fromStatus: bigint;
    toStatus: bigint;
    escalatedBy: string;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintLocationStoredEvent {
  export type InputTuple = [
    complaintId: string,
    pin: string,
    district: string,
    city: string,
    locality: string,
    state: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    pin: string,
    district: string,
    city: string,
    locality: string,
    state: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    pin: string;
    district: string;
    city: string;
    locality: string;
    state: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintRegisteredEvent {
  export type InputTuple = [
    complaintId: string,
    complainantId: string,
    categoryId: string,
    subCategory: string,
    department: string,
    urgency: BigNumberish,
    descriptionHash: BytesLike,
    attachmentHash: BytesLike,
    locationHash: BytesLike,
    isPublic: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    complainantId: string,
    categoryId: string,
    subCategory: string,
    department: string,
    urgency: bigint,
    descriptionHash: string,
    attachmentHash: string,
    locationHash: string,
    isPublic: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    complainantId: string;
    categoryId: string;
    subCategory: string;
    department: string;
    urgency: bigint;
    descriptionHash: string;
    attachmentHash: string;
    locationHash: string;
    isPublic: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintResolvedEvent {
  export type InputTuple = [complaintId: string, timestamp: BigNumberish];
  export type OutputTuple = [complaintId: string, timestamp: bigint];
  export interface OutputObject {
    complaintId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintSlaBreachedEvent {
  export type InputTuple = [
    complaintId: string,
    expectedBy: BigNumberish,
    breachedAt: BigNumberish,
    noteHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    expectedBy: bigint,
    breachedAt: bigint,
    noteHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    expectedBy: bigint;
    breachedAt: bigint;
    noteHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintSlaRecordedEvent {
  export type InputTuple = [
    complaintId: string,
    expectedBy: BigNumberish,
    noteHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    expectedBy: bigint,
    noteHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    expectedBy: bigint;
    noteHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintStatusAuditedEvent {
  export type InputTuple = [
    complaintId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    changedBy: AddressLike,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    oldStatus: bigint,
    newStatus: bigint,
    changedBy: string,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    oldStatus: bigint;
    newStatus: bigint;
    changedBy: string;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintStatusUpdatedEvent {
  export type InputTuple = [
    complaintId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    statusName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    oldStatus: bigint,
    newStatus: bigint,
    statusName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    oldStatus: bigint;
    newStatus: bigint;
    statusName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintUpvotedEvent {
  export type InputTuple = [
    complaintId: string,
    voter: AddressLike,
    newCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    voter: string,
    newCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    voter: string;
    newCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintVerificationCodeCreatedEvent {
  export type InputTuple = [
    complaintId: string,
    verificationCode: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    verificationCode: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    verificationCode: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossDepartmentCorruptionFlaggedEvent {
  export type InputTuple = [
    complaintId: string,
    reassignmentCount: BigNumberish,
    departmentHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    reassignmentCount: bigint,
    departmentHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    reassignmentCount: bigint;
    departmentHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuplicateAssessmentRecordedEvent {
  export type InputTuple = [
    complaintId: string,
    leafHash: BytesLike,
    merkleRoot: BytesLike,
    isDuplicate: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    leafHash: string,
    merkleRoot: string,
    isDuplicate: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    leafHash: string;
    merkleRoot: string;
    isDuplicate: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerkleBatchCommittedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    root: BytesLike,
    batchLabelHash: BytesLike,
    itemCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    root: string,
    batchLabelHash: string,
    itemCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    root: string;
    batchLabelHash: string;
    itemCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    previousOwner: AddressLike,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    previousOwner: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionCertificateIssuedEvent {
  export type InputTuple = [
    complaintId: string,
    recipientId: string,
    certificateHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    recipientId: string,
    certificateHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    recipientId: string;
    certificateHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionCertificateMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    complaintId: string,
    recipientId: string,
    recipientWallet: AddressLike,
    tokenUri: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    complaintId: string,
    recipientId: string,
    recipientWallet: string,
    tokenUri: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    complaintId: string;
    recipientId: string;
    recipientWallet: string;
    tokenUri: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpvoteAddedEvent {
  export type InputTuple = [
    complaintId: string,
    newCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    newCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    newCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserLocationStoredEvent {
  export type InputTuple = [
    userId: string,
    pin: string,
    district: string,
    city: string,
    state: string,
    municipal: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    userId: string,
    pin: string,
    district: string,
    city: string,
    state: string,
    municipal: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    userId: string;
    pin: string;
    district: string;
    city: string;
    state: string;
    municipal: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    userId: string,
    name: string,
    role: string,
    emailHash: BytesLike,
    aadhaarHash: BytesLike,
    locationHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    userId: string,
    name: string,
    role: string,
    emailHash: string,
    aadhaarHash: string,
    locationHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    userId: string;
    name: string;
    role: string;
    emailHash: string;
    aadhaarHash: string;
    locationHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GrievanceContractOptimized extends BaseContract {
  connect(runner?: ContractRunner | null): GrievanceContractOptimized;
  waitForDeployment(): Promise<this>;

  interface: GrievanceContractOptimizedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anonymousIdentityProofVerified: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  anonymousProofVerifier: TypedContractMethod<[], [string], "view">;

  assignComplaint: TypedContractMethod<
    [_complaintId: string, _assignedTo: string],
    [void],
    "nonpayable"
  >;

  authorizedOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  checkComplaintExists: TypedContractMethod<
    [_complaintId: string],
    [boolean],
    "view"
  >;

  checkUserExists: TypedContractMethod<[_userId: string], [boolean], "view">;

  commitMerkleBatch: TypedContractMethod<
    [_root: BytesLike, _itemCount: BigNumberish, _batchLabel: string],
    [bigint],
    "nonpayable"
  >;

  complaintExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  complaints: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        complainantIdHash: string;
        descriptionHash: string;
        attachmentHash: string;
        locationHash: string;
        submissionDate: bigint;
        lastUpdated: bigint;
        upvoteCount: bigint;
        urgencyLevel: bigint;
        statusCode: bigint;
        isPublic: boolean;
      }
    ],
    "view"
  >;

  createAuditLog: TypedContractMethod<
    [
      _logId: string,
      _action: string,
      _userId: string,
      _complaintId: string,
      _details: string
    ],
    [void],
    "nonpayable"
  >;

  createCivicPriority: TypedContractMethod<
    [_priorityId: string, _creatorHash: BytesLike, _endsAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  emitComplaintVerificationCode: TypedContractMethod<
    [_complaintId: string],
    [string],
    "nonpayable"
  >;

  escalateComplaint: TypedContractMethod<
    [_complaintId: string, _toStatus: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  getComplaint: TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.ComplaintStructOutput],
    "view"
  >;

  getComplaintEscalationHistory: TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.EscalationRecordStructOutput[]],
    "view"
  >;

  getComplaintSla: TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.SlaRecordStructOutput],
    "view"
  >;

  getComplaintStatusHistory: TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.StatusAuditEntryStructOutput[]],
    "view"
  >;

  getComplaintVerificationCode: TypedContractMethod<
    [_complaintId: string],
    [string],
    "view"
  >;

  getCounts: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        userCount: bigint;
        complaintCount: bigint;
        auditLogCount: bigint;
      }
    ],
    "view"
  >;

  getResolutionCertificate: TypedContractMethod<
    [_tokenId: BigNumberish],
    [
      [string, string, string] & {
        recipientWallet: string;
        recipientIdHash: string;
        tokenUri: string;
      }
    ],
    "view"
  >;

  getResolutionCertificateTokenByComplaint: TypedContractMethod<
    [_complaintId: string],
    [bigint],
    "view"
  >;

  getUser: TypedContractMethod<
    [_userId: string],
    [GrievanceContractOptimized.UserStructOutput],
    "view"
  >;

  issueResolutionCertificate: TypedContractMethod<
    [_complaintId: string, _recipientId: string],
    [void],
    "nonpayable"
  >;

  issueResolutionCertificateToWallet: TypedContractMethod<
    [
      _complaintId: string,
      _recipientId: string,
      _recipientWallet: AddressLike,
      _tokenUri: string
    ],
    [bigint],
    "nonpayable"
  >;

  markComplaintSlaBreached: TypedContractMethod<
    [_complaintId: string, _note: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordAgentPerformance: TypedContractMethod<
    [
      _agentId: string,
      _complaintId: string,
      _outcomeStatus: BigNumberish,
      _scoreDelta: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  recordComplaintSla: TypedContractMethod<
    [_complaintId: string, _expectedBy: BigNumberish, _note: string],
    [void],
    "nonpayable"
  >;

  recordDuplicateAssessment: TypedContractMethod<
    [
      _complaintId: string,
      _leafHash: BytesLike,
      _merkleRoot: BytesLike,
      _proof: BytesLike[],
      _isDuplicate: boolean
    ],
    [void],
    "nonpayable"
  >;

  registerAnonymousComplaint: TypedContractMethod<
    [
      _complaintId: string,
      _identityCommitment: BytesLike,
      _categoryId: string,
      _subCategory: string,
      _department: string,
      _urgency: BigNumberish,
      _descriptionHash: BytesLike,
      _attachmentHash: BytesLike,
      _locationHash: BytesLike,
      _pin: string,
      _district: string,
      _city: string,
      _locality: string,
      _state: string
    ],
    [void],
    "nonpayable"
  >;

  registerComplaint: TypedContractMethod<
    [
      _complaintId: string,
      _complainantId: string,
      _categoryId: string,
      _subCategory: string,
      _department: string,
      _urgency: BigNumberish,
      _descriptionHash: BytesLike,
      _attachmentHash: BytesLike,
      _locationHash: BytesLike,
      _isPublic: boolean,
      _pin: string,
      _district: string,
      _city: string,
      _locality: string,
      _state: string
    ],
    [void],
    "nonpayable"
  >;

  registerUser: TypedContractMethod<
    [
      _userId: string,
      _name: string,
      _role: string,
      _emailHash: BytesLike,
      _aadhaarHash: BytesLike,
      _locationHash: BytesLike,
      _pin: string,
      _district: string,
      _city: string,
      _state: string,
      _municipal: string
    ],
    [void],
    "nonpayable"
  >;

  resolveComplaint: TypedContractMethod<
    [_complaintId: string],
    [void],
    "nonpayable"
  >;

  setAnonymousProofVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  setAuthorizedOperator: TypedContractMethod<
    [_operator: AddressLike, _isAuthorized: boolean],
    [void],
    "nonpayable"
  >;

  totalAuditLogs: TypedContractMethod<[], [bigint], "view">;

  totalComplaints: TypedContractMethod<[], [bigint], "view">;

  totalMerkleBatches: TypedContractMethod<[], [bigint], "view">;

  totalResolutionCertificates: TypedContractMethod<[], [bigint], "view">;

  totalUsers: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateComplaintStatus: TypedContractMethod<
    [_complaintId: string, _newStatus: BigNumberish, _statusName: string],
    [void],
    "nonpayable"
  >;

  updateComplaintStatusWithReason: TypedContractMethod<
    [
      _complaintId: string,
      _newStatus: BigNumberish,
      _statusName: string,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;

  updateUpvoteCount: TypedContractMethod<
    [_complaintId: string, _newCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  upvoteComplaint: TypedContractMethod<
    [_complaintId: string],
    [void],
    "nonpayable"
  >;

  userExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  users: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        emailHash: string;
        aadhaarHash: string;
        locationHash: string;
        registrationDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  verifyAnonymousIdentityProof: TypedContractMethod<
    [_identityCommitment: BytesLike, _proof: BytesLike],
    [boolean],
    "nonpayable"
  >;

  verifyHash: TypedContractMethod<
    [_complaintId: string, _descriptionHash: BytesLike],
    [boolean],
    "view"
  >;

  verifyMerkleProof: TypedContractMethod<
    [_leaf: BytesLike, _root: BytesLike, _proof: BytesLike[]],
    [boolean],
    "view"
  >;

  voteCivicPriority: TypedContractMethod<
    [_priorityId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anonymousIdentityProofVerified"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "anonymousProofVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assignComplaint"
  ): TypedContractMethod<
    [_complaintId: string, _assignedTo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkComplaintExists"
  ): TypedContractMethod<[_complaintId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkUserExists"
  ): TypedContractMethod<[_userId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "commitMerkleBatch"
  ): TypedContractMethod<
    [_root: BytesLike, _itemCount: BigNumberish, _batchLabel: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "complaintExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "complaints"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        complainantIdHash: string;
        descriptionHash: string;
        attachmentHash: string;
        locationHash: string;
        submissionDate: bigint;
        lastUpdated: bigint;
        upvoteCount: bigint;
        urgencyLevel: bigint;
        statusCode: bigint;
        isPublic: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAuditLog"
  ): TypedContractMethod<
    [
      _logId: string,
      _action: string,
      _userId: string,
      _complaintId: string,
      _details: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCivicPriority"
  ): TypedContractMethod<
    [_priorityId: string, _creatorHash: BytesLike, _endsAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitComplaintVerificationCode"
  ): TypedContractMethod<[_complaintId: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "escalateComplaint"
  ): TypedContractMethod<
    [_complaintId: string, _toStatus: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getComplaint"
  ): TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.ComplaintStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getComplaintEscalationHistory"
  ): TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.EscalationRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getComplaintSla"
  ): TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.SlaRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getComplaintStatusHistory"
  ): TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.StatusAuditEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getComplaintVerificationCode"
  ): TypedContractMethod<[_complaintId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getCounts"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        userCount: bigint;
        complaintCount: bigint;
        auditLogCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResolutionCertificate"
  ): TypedContractMethod<
    [_tokenId: BigNumberish],
    [
      [string, string, string] & {
        recipientWallet: string;
        recipientIdHash: string;
        tokenUri: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResolutionCertificateTokenByComplaint"
  ): TypedContractMethod<[_complaintId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [_userId: string],
    [GrievanceContractOptimized.UserStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueResolutionCertificate"
  ): TypedContractMethod<
    [_complaintId: string, _recipientId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issueResolutionCertificateToWallet"
  ): TypedContractMethod<
    [
      _complaintId: string,
      _recipientId: string,
      _recipientWallet: AddressLike,
      _tokenUri: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markComplaintSlaBreached"
  ): TypedContractMethod<
    [_complaintId: string, _note: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordAgentPerformance"
  ): TypedContractMethod<
    [
      _agentId: string,
      _complaintId: string,
      _outcomeStatus: BigNumberish,
      _scoreDelta: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordComplaintSla"
  ): TypedContractMethod<
    [_complaintId: string, _expectedBy: BigNumberish, _note: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordDuplicateAssessment"
  ): TypedContractMethod<
    [
      _complaintId: string,
      _leafHash: BytesLike,
      _merkleRoot: BytesLike,
      _proof: BytesLike[],
      _isDuplicate: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAnonymousComplaint"
  ): TypedContractMethod<
    [
      _complaintId: string,
      _identityCommitment: BytesLike,
      _categoryId: string,
      _subCategory: string,
      _department: string,
      _urgency: BigNumberish,
      _descriptionHash: BytesLike,
      _attachmentHash: BytesLike,
      _locationHash: BytesLike,
      _pin: string,
      _district: string,
      _city: string,
      _locality: string,
      _state: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerComplaint"
  ): TypedContractMethod<
    [
      _complaintId: string,
      _complainantId: string,
      _categoryId: string,
      _subCategory: string,
      _department: string,
      _urgency: BigNumberish,
      _descriptionHash: BytesLike,
      _attachmentHash: BytesLike,
      _locationHash: BytesLike,
      _isPublic: boolean,
      _pin: string,
      _district: string,
      _city: string,
      _locality: string,
      _state: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [
      _userId: string,
      _name: string,
      _role: string,
      _emailHash: BytesLike,
      _aadhaarHash: BytesLike,
      _locationHash: BytesLike,
      _pin: string,
      _district: string,
      _city: string,
      _state: string,
      _municipal: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveComplaint"
  ): TypedContractMethod<[_complaintId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAnonymousProofVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedOperator"
  ): TypedContractMethod<
    [_operator: AddressLike, _isAuthorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAuditLogs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalComplaints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalMerkleBatches"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalResolutionCertificates"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateComplaintStatus"
  ): TypedContractMethod<
    [_complaintId: string, _newStatus: BigNumberish, _statusName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateComplaintStatusWithReason"
  ): TypedContractMethod<
    [
      _complaintId: string,
      _newStatus: BigNumberish,
      _statusName: string,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUpvoteCount"
  ): TypedContractMethod<
    [_complaintId: string, _newCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upvoteComplaint"
  ): TypedContractMethod<[_complaintId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        emailHash: string;
        aadhaarHash: string;
        locationHash: string;
        registrationDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyAnonymousIdentityProof"
  ): TypedContractMethod<
    [_identityCommitment: BytesLike, _proof: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [_complaintId: string, _descriptionHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyMerkleProof"
  ): TypedContractMethod<
    [_leaf: BytesLike, _root: BytesLike, _proof: BytesLike[]],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "voteCivicPriority"
  ): TypedContractMethod<[_priorityId: string], [void], "nonpayable">;

  getEvent(
    key: "AgentPerformanceRecorded"
  ): TypedContractEvent<
    AgentPerformanceRecordedEvent.InputTuple,
    AgentPerformanceRecordedEvent.OutputTuple,
    AgentPerformanceRecordedEvent.OutputObject
  >;
  getEvent(
    key: "AnonymousComplaintRegistered"
  ): TypedContractEvent<
    AnonymousComplaintRegisteredEvent.InputTuple,
    AnonymousComplaintRegisteredEvent.OutputTuple,
    AnonymousComplaintRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AnonymousIdentityProofVerified"
  ): TypedContractEvent<
    AnonymousIdentityProofVerifiedEvent.InputTuple,
    AnonymousIdentityProofVerifiedEvent.OutputTuple,
    AnonymousIdentityProofVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "AnonymousProofVerifierUpdated"
  ): TypedContractEvent<
    AnonymousProofVerifierUpdatedEvent.InputTuple,
    AnonymousProofVerifierUpdatedEvent.OutputTuple,
    AnonymousProofVerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AuditLogCreated"
  ): TypedContractEvent<
    AuditLogCreatedEvent.InputTuple,
    AuditLogCreatedEvent.OutputTuple,
    AuditLogCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuthorizedOperatorUpdated"
  ): TypedContractEvent<
    AuthorizedOperatorUpdatedEvent.InputTuple,
    AuthorizedOperatorUpdatedEvent.OutputTuple,
    AuthorizedOperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CivicPriorityCreated"
  ): TypedContractEvent<
    CivicPriorityCreatedEvent.InputTuple,
    CivicPriorityCreatedEvent.OutputTuple,
    CivicPriorityCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CivicPriorityVoted"
  ): TypedContractEvent<
    CivicPriorityVotedEvent.InputTuple,
    CivicPriorityVotedEvent.OutputTuple,
    CivicPriorityVotedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintAssigned"
  ): TypedContractEvent<
    ComplaintAssignedEvent.InputTuple,
    ComplaintAssignedEvent.OutputTuple,
    ComplaintAssignedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintEscalated"
  ): TypedContractEvent<
    ComplaintEscalatedEvent.InputTuple,
    ComplaintEscalatedEvent.OutputTuple,
    ComplaintEscalatedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintLocationStored"
  ): TypedContractEvent<
    ComplaintLocationStoredEvent.InputTuple,
    ComplaintLocationStoredEvent.OutputTuple,
    ComplaintLocationStoredEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintRegistered"
  ): TypedContractEvent<
    ComplaintRegisteredEvent.InputTuple,
    ComplaintRegisteredEvent.OutputTuple,
    ComplaintRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintResolved"
  ): TypedContractEvent<
    ComplaintResolvedEvent.InputTuple,
    ComplaintResolvedEvent.OutputTuple,
    ComplaintResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintSlaBreached"
  ): TypedContractEvent<
    ComplaintSlaBreachedEvent.InputTuple,
    ComplaintSlaBreachedEvent.OutputTuple,
    ComplaintSlaBreachedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintSlaRecorded"
  ): TypedContractEvent<
    ComplaintSlaRecordedEvent.InputTuple,
    ComplaintSlaRecordedEvent.OutputTuple,
    ComplaintSlaRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintStatusAudited"
  ): TypedContractEvent<
    ComplaintStatusAuditedEvent.InputTuple,
    ComplaintStatusAuditedEvent.OutputTuple,
    ComplaintStatusAuditedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintStatusUpdated"
  ): TypedContractEvent<
    ComplaintStatusUpdatedEvent.InputTuple,
    ComplaintStatusUpdatedEvent.OutputTuple,
    ComplaintStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintUpvoted"
  ): TypedContractEvent<
    ComplaintUpvotedEvent.InputTuple,
    ComplaintUpvotedEvent.OutputTuple,
    ComplaintUpvotedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintVerificationCodeCreated"
  ): TypedContractEvent<
    ComplaintVerificationCodeCreatedEvent.InputTuple,
    ComplaintVerificationCodeCreatedEvent.OutputTuple,
    ComplaintVerificationCodeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CrossDepartmentCorruptionFlagged"
  ): TypedContractEvent<
    CrossDepartmentCorruptionFlaggedEvent.InputTuple,
    CrossDepartmentCorruptionFlaggedEvent.OutputTuple,
    CrossDepartmentCorruptionFlaggedEvent.OutputObject
  >;
  getEvent(
    key: "DuplicateAssessmentRecorded"
  ): TypedContractEvent<
    DuplicateAssessmentRecordedEvent.InputTuple,
    DuplicateAssessmentRecordedEvent.OutputTuple,
    DuplicateAssessmentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "MerkleBatchCommitted"
  ): TypedContractEvent<
    MerkleBatchCommittedEvent.InputTuple,
    MerkleBatchCommittedEvent.OutputTuple,
    MerkleBatchCommittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionCertificateIssued"
  ): TypedContractEvent<
    ResolutionCertificateIssuedEvent.InputTuple,
    ResolutionCertificateIssuedEvent.OutputTuple,
    ResolutionCertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionCertificateMinted"
  ): TypedContractEvent<
    ResolutionCertificateMintedEvent.InputTuple,
    ResolutionCertificateMintedEvent.OutputTuple,
    ResolutionCertificateMintedEvent.OutputObject
  >;
  getEvent(
    key: "UpvoteAdded"
  ): TypedContractEvent<
    UpvoteAddedEvent.InputTuple,
    UpvoteAddedEvent.OutputTuple,
    UpvoteAddedEvent.OutputObject
  >;
  getEvent(
    key: "UserLocationStored"
  ): TypedContractEvent<
    UserLocationStoredEvent.InputTuple,
    UserLocationStoredEvent.OutputTuple,
    UserLocationStoredEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "AgentPerformanceRecorded(string,string,uint32,uint32,uint32,uint32,uint256)": TypedContractEvent<
      AgentPerformanceRecordedEvent.InputTuple,
      AgentPerformanceRecordedEvent.OutputTuple,
      AgentPerformanceRecordedEvent.OutputObject
    >;
    AgentPerformanceRecorded: TypedContractEvent<
      AgentPerformanceRecordedEvent.InputTuple,
      AgentPerformanceRecordedEvent.OutputTuple,
      AgentPerformanceRecordedEvent.OutputObject
    >;

    "AnonymousComplaintRegistered(string,bytes32,bytes32,uint256)": TypedContractEvent<
      AnonymousComplaintRegisteredEvent.InputTuple,
      AnonymousComplaintRegisteredEvent.OutputTuple,
      AnonymousComplaintRegisteredEvent.OutputObject
    >;
    AnonymousComplaintRegistered: TypedContractEvent<
      AnonymousComplaintRegisteredEvent.InputTuple,
      AnonymousComplaintRegisteredEvent.OutputTuple,
      AnonymousComplaintRegisteredEvent.OutputObject
    >;

    "AnonymousIdentityProofVerified(bytes32,address,uint256)": TypedContractEvent<
      AnonymousIdentityProofVerifiedEvent.InputTuple,
      AnonymousIdentityProofVerifiedEvent.OutputTuple,
      AnonymousIdentityProofVerifiedEvent.OutputObject
    >;
    AnonymousIdentityProofVerified: TypedContractEvent<
      AnonymousIdentityProofVerifiedEvent.InputTuple,
      AnonymousIdentityProofVerifiedEvent.OutputTuple,
      AnonymousIdentityProofVerifiedEvent.OutputObject
    >;

    "AnonymousProofVerifierUpdated(address,uint256)": TypedContractEvent<
      AnonymousProofVerifierUpdatedEvent.InputTuple,
      AnonymousProofVerifierUpdatedEvent.OutputTuple,
      AnonymousProofVerifierUpdatedEvent.OutputObject
    >;
    AnonymousProofVerifierUpdated: TypedContractEvent<
      AnonymousProofVerifierUpdatedEvent.InputTuple,
      AnonymousProofVerifierUpdatedEvent.OutputTuple,
      AnonymousProofVerifierUpdatedEvent.OutputObject
    >;

    "AuditLogCreated(string,string,string,string,string,uint256)": TypedContractEvent<
      AuditLogCreatedEvent.InputTuple,
      AuditLogCreatedEvent.OutputTuple,
      AuditLogCreatedEvent.OutputObject
    >;
    AuditLogCreated: TypedContractEvent<
      AuditLogCreatedEvent.InputTuple,
      AuditLogCreatedEvent.OutputTuple,
      AuditLogCreatedEvent.OutputObject
    >;

    "AuthorizedOperatorUpdated(address,bool,uint256)": TypedContractEvent<
      AuthorizedOperatorUpdatedEvent.InputTuple,
      AuthorizedOperatorUpdatedEvent.OutputTuple,
      AuthorizedOperatorUpdatedEvent.OutputObject
    >;
    AuthorizedOperatorUpdated: TypedContractEvent<
      AuthorizedOperatorUpdatedEvent.InputTuple,
      AuthorizedOperatorUpdatedEvent.OutputTuple,
      AuthorizedOperatorUpdatedEvent.OutputObject
    >;

    "CivicPriorityCreated(string,bytes32,uint64,uint256)": TypedContractEvent<
      CivicPriorityCreatedEvent.InputTuple,
      CivicPriorityCreatedEvent.OutputTuple,
      CivicPriorityCreatedEvent.OutputObject
    >;
    CivicPriorityCreated: TypedContractEvent<
      CivicPriorityCreatedEvent.InputTuple,
      CivicPriorityCreatedEvent.OutputTuple,
      CivicPriorityCreatedEvent.OutputObject
    >;

    "CivicPriorityVoted(string,address,uint32,uint256)": TypedContractEvent<
      CivicPriorityVotedEvent.InputTuple,
      CivicPriorityVotedEvent.OutputTuple,
      CivicPriorityVotedEvent.OutputObject
    >;
    CivicPriorityVoted: TypedContractEvent<
      CivicPriorityVotedEvent.InputTuple,
      CivicPriorityVotedEvent.OutputTuple,
      CivicPriorityVotedEvent.OutputObject
    >;

    "ComplaintAssigned(string,string,uint256)": TypedContractEvent<
      ComplaintAssignedEvent.InputTuple,
      ComplaintAssignedEvent.OutputTuple,
      ComplaintAssignedEvent.OutputObject
    >;
    ComplaintAssigned: TypedContractEvent<
      ComplaintAssignedEvent.InputTuple,
      ComplaintAssignedEvent.OutputTuple,
      ComplaintAssignedEvent.OutputObject
    >;

    "ComplaintEscalated(string,uint8,uint8,address,bytes32,uint256)": TypedContractEvent<
      ComplaintEscalatedEvent.InputTuple,
      ComplaintEscalatedEvent.OutputTuple,
      ComplaintEscalatedEvent.OutputObject
    >;
    ComplaintEscalated: TypedContractEvent<
      ComplaintEscalatedEvent.InputTuple,
      ComplaintEscalatedEvent.OutputTuple,
      ComplaintEscalatedEvent.OutputObject
    >;

    "ComplaintLocationStored(string,string,string,string,string,string,uint256)": TypedContractEvent<
      ComplaintLocationStoredEvent.InputTuple,
      ComplaintLocationStoredEvent.OutputTuple,
      ComplaintLocationStoredEvent.OutputObject
    >;
    ComplaintLocationStored: TypedContractEvent<
      ComplaintLocationStoredEvent.InputTuple,
      ComplaintLocationStoredEvent.OutputTuple,
      ComplaintLocationStoredEvent.OutputObject
    >;

    "ComplaintRegistered(string,string,string,string,string,uint8,bytes32,bytes32,bytes32,bool,uint256)": TypedContractEvent<
      ComplaintRegisteredEvent.InputTuple,
      ComplaintRegisteredEvent.OutputTuple,
      ComplaintRegisteredEvent.OutputObject
    >;
    ComplaintRegistered: TypedContractEvent<
      ComplaintRegisteredEvent.InputTuple,
      ComplaintRegisteredEvent.OutputTuple,
      ComplaintRegisteredEvent.OutputObject
    >;

    "ComplaintResolved(string,uint256)": TypedContractEvent<
      ComplaintResolvedEvent.InputTuple,
      ComplaintResolvedEvent.OutputTuple,
      ComplaintResolvedEvent.OutputObject
    >;
    ComplaintResolved: TypedContractEvent<
      ComplaintResolvedEvent.InputTuple,
      ComplaintResolvedEvent.OutputTuple,
      ComplaintResolvedEvent.OutputObject
    >;

    "ComplaintSlaBreached(string,uint64,uint64,bytes32,uint256)": TypedContractEvent<
      ComplaintSlaBreachedEvent.InputTuple,
      ComplaintSlaBreachedEvent.OutputTuple,
      ComplaintSlaBreachedEvent.OutputObject
    >;
    ComplaintSlaBreached: TypedContractEvent<
      ComplaintSlaBreachedEvent.InputTuple,
      ComplaintSlaBreachedEvent.OutputTuple,
      ComplaintSlaBreachedEvent.OutputObject
    >;

    "ComplaintSlaRecorded(string,uint64,bytes32,uint256)": TypedContractEvent<
      ComplaintSlaRecordedEvent.InputTuple,
      ComplaintSlaRecordedEvent.OutputTuple,
      ComplaintSlaRecordedEvent.OutputObject
    >;
    ComplaintSlaRecorded: TypedContractEvent<
      ComplaintSlaRecordedEvent.InputTuple,
      ComplaintSlaRecordedEvent.OutputTuple,
      ComplaintSlaRecordedEvent.OutputObject
    >;

    "ComplaintStatusAudited(string,uint8,uint8,address,bytes32,uint256)": TypedContractEvent<
      ComplaintStatusAuditedEvent.InputTuple,
      ComplaintStatusAuditedEvent.OutputTuple,
      ComplaintStatusAuditedEvent.OutputObject
    >;
    ComplaintStatusAudited: TypedContractEvent<
      ComplaintStatusAuditedEvent.InputTuple,
      ComplaintStatusAuditedEvent.OutputTuple,
      ComplaintStatusAuditedEvent.OutputObject
    >;

    "ComplaintStatusUpdated(string,uint8,uint8,string,uint256)": TypedContractEvent<
      ComplaintStatusUpdatedEvent.InputTuple,
      ComplaintStatusUpdatedEvent.OutputTuple,
      ComplaintStatusUpdatedEvent.OutputObject
    >;
    ComplaintStatusUpdated: TypedContractEvent<
      ComplaintStatusUpdatedEvent.InputTuple,
      ComplaintStatusUpdatedEvent.OutputTuple,
      ComplaintStatusUpdatedEvent.OutputObject
    >;

    "ComplaintUpvoted(string,address,uint32,uint256)": TypedContractEvent<
      ComplaintUpvotedEvent.InputTuple,
      ComplaintUpvotedEvent.OutputTuple,
      ComplaintUpvotedEvent.OutputObject
    >;
    ComplaintUpvoted: TypedContractEvent<
      ComplaintUpvotedEvent.InputTuple,
      ComplaintUpvotedEvent.OutputTuple,
      ComplaintUpvotedEvent.OutputObject
    >;

    "ComplaintVerificationCodeCreated(string,bytes32,uint256)": TypedContractEvent<
      ComplaintVerificationCodeCreatedEvent.InputTuple,
      ComplaintVerificationCodeCreatedEvent.OutputTuple,
      ComplaintVerificationCodeCreatedEvent.OutputObject
    >;
    ComplaintVerificationCodeCreated: TypedContractEvent<
      ComplaintVerificationCodeCreatedEvent.InputTuple,
      ComplaintVerificationCodeCreatedEvent.OutputTuple,
      ComplaintVerificationCodeCreatedEvent.OutputObject
    >;

    "CrossDepartmentCorruptionFlagged(string,uint32,bytes32,uint256)": TypedContractEvent<
      CrossDepartmentCorruptionFlaggedEvent.InputTuple,
      CrossDepartmentCorruptionFlaggedEvent.OutputTuple,
      CrossDepartmentCorruptionFlaggedEvent.OutputObject
    >;
    CrossDepartmentCorruptionFlagged: TypedContractEvent<
      CrossDepartmentCorruptionFlaggedEvent.InputTuple,
      CrossDepartmentCorruptionFlaggedEvent.OutputTuple,
      CrossDepartmentCorruptionFlaggedEvent.OutputObject
    >;

    "DuplicateAssessmentRecorded(string,bytes32,bytes32,bool,uint256)": TypedContractEvent<
      DuplicateAssessmentRecordedEvent.InputTuple,
      DuplicateAssessmentRecordedEvent.OutputTuple,
      DuplicateAssessmentRecordedEvent.OutputObject
    >;
    DuplicateAssessmentRecorded: TypedContractEvent<
      DuplicateAssessmentRecordedEvent.InputTuple,
      DuplicateAssessmentRecordedEvent.OutputTuple,
      DuplicateAssessmentRecordedEvent.OutputObject
    >;

    "MerkleBatchCommitted(uint256,bytes32,bytes32,uint32,uint256)": TypedContractEvent<
      MerkleBatchCommittedEvent.InputTuple,
      MerkleBatchCommittedEvent.OutputTuple,
      MerkleBatchCommittedEvent.OutputObject
    >;
    MerkleBatchCommitted: TypedContractEvent<
      MerkleBatchCommittedEvent.InputTuple,
      MerkleBatchCommittedEvent.OutputTuple,
      MerkleBatchCommittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ResolutionCertificateIssued(string,string,bytes32,uint256)": TypedContractEvent<
      ResolutionCertificateIssuedEvent.InputTuple,
      ResolutionCertificateIssuedEvent.OutputTuple,
      ResolutionCertificateIssuedEvent.OutputObject
    >;
    ResolutionCertificateIssued: TypedContractEvent<
      ResolutionCertificateIssuedEvent.InputTuple,
      ResolutionCertificateIssuedEvent.OutputTuple,
      ResolutionCertificateIssuedEvent.OutputObject
    >;

    "ResolutionCertificateMinted(uint256,string,string,address,string,uint256)": TypedContractEvent<
      ResolutionCertificateMintedEvent.InputTuple,
      ResolutionCertificateMintedEvent.OutputTuple,
      ResolutionCertificateMintedEvent.OutputObject
    >;
    ResolutionCertificateMinted: TypedContractEvent<
      ResolutionCertificateMintedEvent.InputTuple,
      ResolutionCertificateMintedEvent.OutputTuple,
      ResolutionCertificateMintedEvent.OutputObject
    >;

    "UpvoteAdded(string,uint32,uint256)": TypedContractEvent<
      UpvoteAddedEvent.InputTuple,
      UpvoteAddedEvent.OutputTuple,
      UpvoteAddedEvent.OutputObject
    >;
    UpvoteAdded: TypedContractEvent<
      UpvoteAddedEvent.InputTuple,
      UpvoteAddedEvent.OutputTuple,
      UpvoteAddedEvent.OutputObject
    >;

    "UserLocationStored(string,string,string,string,string,string,uint256)": TypedContractEvent<
      UserLocationStoredEvent.InputTuple,
      UserLocationStoredEvent.OutputTuple,
      UserLocationStoredEvent.OutputObject
    >;
    UserLocationStored: TypedContractEvent<
      UserLocationStoredEvent.InputTuple,
      UserLocationStoredEvent.OutputTuple,
      UserLocationStoredEvent.OutputObject
    >;

    "UserRegistered(string,string,string,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
