/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GrievanceContractOptimized } from "./GrievanceContractOptimized";
export type { IAnonymousProofVerifier } from "./IAnonymousProofVerifier";
