/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAnonymousProofVerifier,
  IAnonymousProofVerifierInterface,
} from "../../GrievanceContract.sol/IAnonymousProofVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "identityCommitment",
        type: "bytes32",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAnonymousProofVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IAnonymousProofVerifierInterface {
    return new Interface(_abi) as IAnonymousProofVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAnonymousProofVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAnonymousProofVerifier;
  }
}
