/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  MockAnonymousProofVerifier,
  MockAnonymousProofVerifierInterface,
} from "../MockAnonymousProofVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "_shouldVerify",
        type: "bool",
      },
    ],
    name: "setShouldVerify",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461002257600160ff19600054161760005560eb90816100288239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c80630c54fb0614608757631858cb5b14603257600080fd5b34607f576040366003190112607f5760043567ffffffffffffffff80821160835736602383011215608357816004013590811160835736910160240111607f5760ff602092541615158152f35b5080fd5b8380fd5b823460b257602036600319011260b257600435801515809103607f5760ff8019835416911617815580f35b80fdfea264697066735822122080f15c848cdf9b39ee991685cd752b303eb7a5999c88d69165def134ccef98a264736f6c63430008130033";

type MockAnonymousProofVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockAnonymousProofVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockAnonymousProofVerifier__factory extends ContractFactory {
  constructor(...args: MockAnonymousProofVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockAnonymousProofVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockAnonymousProofVerifier__factory {
    return super.connect(runner) as MockAnonymousProofVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockAnonymousProofVerifierInterface {
    return new Interface(_abi) as MockAnonymousProofVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockAnonymousProofVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockAnonymousProofVerifier;
  }
}
