# This file should be encrypted with ansible-vault
# Run: ansible-vault encrypt vars/secrets.yml
# 
# AWS Secrets Manager Credentials
aws_access_key_id: "AKIAZ53VJYCLAGVGCIWC"
aws_secret_access_key: "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"
